### PR TITLE
Select the gateway with the lowest metric on Windows

### LINKED ISSUE #15: Windows: The gateway is not from external card
When a computer has virtual network adapters with a gateway, it's selecting the first that finds, but not necessarily is the gateway of the external card.

Example: after run `wmic path Win32_NetworkAdapterConfiguration where IPEnabled=true get DefaultIPGateway,Index /format:table` in windows I get this response:
```
3 
{"0.0.0.0"} 5 
{"192.168.1.1", "fe80::dafb:5eff:fe33:3489"} 6 
8
```

and after parse it the result is `0.0.0.0`, but the gateway of the external card is `192.168.1.1`

### PR DESCRIPTION
**Pull request by eycorsican**
May fix #15

### CODE REVIEW

**Comment by silverwind** [comment]
Some lint errors:

````
win32.js
  15:3   error  Unexpected var, use let or const instead  no-var
  17:56  error  Strings must use doublequote              quotes
  17:74  error  Strings must use doublequote              quotes
```

**Comment by silverwind** [comment]
Otherwise, approach looks good.

**Comment by eycorsican** [comment]
Lint errors fixed.

It's worth to note that this PR fixes the case where there are multiple default routes to their own gateways, but the current implementation still fails when there are multiple default routes with different metrics to the SAME gateway, though it a rare case.

**Comment by silverwind** [comment]
Merged this in https://github.com/silverwind/default-gateway/commit/771706d18779d803eeab960c35fd17cd9046360b and did a rework of the parsing in https://github.com/silverwind/default-gateway/commit/1b6d124ab9811438db1d670fcdb30445814634ab.

Your version did not support IPv6 which I've added. Also, it seems the final metric seen in `netstat -nr` is the sum of GatewayCostMetric and IPConnectionMetric, so I added that as well.

Maybe you can confirm that current `master` branch works for you.

**Comment by eycorsican** [comment]
`master` works well for me :)

**Comment by silverwind** [comment]
Thanks, released in `default-gateway@5.0.3`.

**Pull request closed without merging**
