### PR TITLE
Add FreeBSD support

### PR DESCRIPTION
**Pull request by karli-sjoberg**
Used "darwin.js" as a template, which worked great, except for some very minor adjustments. Tested to the point of "Works for me™" :)

### CODE REVIEW

**Comment by silverwind** [comment]
Thanks! Could you also update the `os` and `files` arrays in `package.json`? Just commit it and push to the same branch.

**Comment by karli-sjoberg** [comment]
Right, sh$t I forgot about that. I'll get on it right away!

**Comment by karli-sjoberg** [comment]
Done!

**Comment by silverwind** [comment]
Okay, I'll test this as soon as my FreeBSD VM finishes compiling stuff.

**Comment by silverwind** [comment]
Thanks! Confirmed working. It's released as v2.2.0.

**Comment by karli-sjoberg** [comment]
Awesome, now I have installed TheForeman again, thanks!

**Pull request merged**
