### PR TITLE
Create AIX mainline support 

### PR DESCRIPTION
**Pull request by ThePrez**
Addresses issue #5.

I tested and verified that the sunos implementation works for mainline AIX, since the netstat output is the same format. So, I just have it use the sunos module on AIX. 

I tried several ways to do this `if` logic, including burying all the logic in the aix.js module, creating a new module and dynamically exporting the proper entry point from aix.js, and a couple others. In my opinion, this was the cleanest way, but we can refactor the best way you see fit. 

Thanks!

### CODE REVIEW

**Comment by silverwind** [comment]
Approach seems fine, I probably will refactor this `netstat` parsing across platforms later to reduce code duplication. The branch seems to be in conflict, can you rebase?

**Comment by silverwind** [comment]
Also need to update `package.json` to include the renamed file.

**Comment by ThePrez** [comment]
Oops! Sorry for missing package.json

**Comment by silverwind** [comment]
I take it `make test` passes on AIX? If you do not have IPv6, run `CI=true make test` to skip it.

**Comment by ThePrez** [comment]
Yep, make test is clean 
(sorry for the earlier linting errors, for some reason I was going straight to `node --pending-deprecation --trace-deprecation --throw-deprecation --trace-warnings test.js`)

**Pull request merged**
